"""Added project id to collection

Revision ID: 0b4e7679eb90
Revises: 4f6e3b6cbaec
Create Date: 2026-08-27 12:58:54.768666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4e7679eb90'
down_revision = '4f6e3b6cbaec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('project_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_column('collections', 'project_id')
    # ### end Alembic commands ###
